name: meby
description: MeetBy descrição
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^3.2.2
  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.14
  firebase_auth: ^0.16.1
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.5.1
  cloud_firestore: ^0.13.6
  provider: ^4.1.3
  get_it: ^4.0.2
  firebase_storage: ^3.1.6
  image_cropper: ^1.2.3
  image_picker: ^0.6.7+1
  equatable: ^1.2.0
  location_permissions: ^3.0.0+1
  geolocator: ^5.3.2+2
  flutter_instagram_image_picker: ^0.3.1
  firebase_database: ^3.1.6
  async: ^2.4.1
  flutter_slidable: ^0.5.4
  share: ^0.6.4+3
  one_context: ^0.4.0
  connectivity: ^0.4.8+6
  firebase_messaging: ^6.0.16
  flutter_local_notifications: ^1.4.4+1
  url_launcher: ^5.4.11
  firebase_dynamic_links: ^0.5.1
  flutter_screenutil: ^2.3.0
  overlay_support: ^1.0.5
  flutter_localizations:
    sdk: flutter
  contacts_service: ^0.4.6
  permission_handler: ^5.0.1+1
  get_storage: ^1.2.1
  native_pdf_view: ^3.6.2
  mask_text_input_formatter: ^1.0.7
  flutter_email_sender: ^3.0.1
  tutorial_coach_mark: ^0.3.0
  expandable: ^4.1.4
  date_text_masked: ^1.0.0
  datetime_picker_formfield: ^1.0.0
  flutter_web_auth: ^0.2.4
  sentry: ^3.0.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/foreground.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/whatsapp.png
  - assets/images/facebook.png
  - assets/images/gmail.png
  - assets/images/email.png
  - assets/images/instagram.png
  - assets/images/linkedin.png
  - assets/images/spotify.png
  - assets/images/twitter.png
  - assets/images/youtube.png
  - assets/images/icones_azul_Agenda.png
  - assets/images/icones_azul_Hamburguer.png
  - assets/images/icones_azul_Editar.png
  - assets/images/icones_azul_Seguranca.png
  - assets/images/icones_azul_Sair da conta.png
  - assets/images/compartilhar.png
  - assets/images/MeetBy-PNG-azul_horizontal.png
  - assets/images/MeetBy-PNG-azul_simbolo.png
  - assets/images/icone_pesquisa.png
  - assets/images/icone_Pesquisa.svg
  - assets/images/iconepesquisa.png
  - assets/images/icones_azul_Deletar.png
  - assets/images/desert.png
  - assets/images/aceitar.png
  - assets/images/recusar.png
  - assets/images/splash.png
  - assets/images/conta2.png
  - assets/images/meu_perfil_cinza.png
  - assets/images/meu_perfil_azul.png
  - assets/images/solicitacoes_cinza.png
  - assets/images/solicitacoes_azul.png
  - assets/politicadeprivacidade.pdf
  - assets/termosdeuso.pdf
  - assets/images/google.png
  - assets/images/salvar_on.png
  - assets/images/salvar_off.png
  - assets/images/mebyconta.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: Segoe
      fonts:
        - asset: assets/fonts/segoe.ttf
        - asset: assets/fonts/segoebold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
